#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:3.1 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["src/Microsoft.Health.Fhir.Anonymizer.Stu3.CommandLineTool/Microsoft.Health.Fhir.Anonymizer.Stu3.CommandLineTool.csproj", "src/Microsoft.Health.Fhir.Anonymizer.Stu3.CommandLineTool/"]
COPY ["src/Microsoft.Health.Fhir.Anonymizer.Stu3.Core/Microsoft.Health.Fhir.Anonymizer.Stu3.Core.csproj", "src/Microsoft.Health.Fhir.Anonymizer.Stu3.Core/"]
RUN dotnet restore "src/Microsoft.Health.Fhir.Anonymizer.Stu3.CommandLineTool/Microsoft.Health.Fhir.Anonymizer.Stu3.CommandLineTool.csproj"
COPY . .
WORKDIR "/src/src/Microsoft.Health.Fhir.Anonymizer.Stu3.CommandLineTool"
RUN dotnet build "Microsoft.Health.Fhir.Anonymizer.Stu3.CommandLineTool.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Microsoft.Health.Fhir.Anonymizer.Stu3.CommandLineTool.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Microsoft.Health.Fhir.Anonymizer.Stu3.CommandLineTool.dll"]